---
title: "Untitled"
output: html_document
date: "2024-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
in_df <- in_solar_df
```

```{r}
# Change single double axis array to single axis for simplicity
in_df$Class <- ifelse(in_df$Class=="double_axis", "single_axis", in_df$Class)
# Set colors
fixedAxisColor = "#D3D3D3"
singleAxisColor = "#708090"
# Remove geometry
in_df$geometry = NULL
start_install_year = in_df$Year %>% range() %>% min() %>% as.numeric() # first year of installation in dataset 
end_install_year  =  in_df$Year %>% range() %>% max() %>% as.numeric() # last year of installation in dataset (same as start year if only one array)
# Make plot function
getPlot_Array_Tech_Dist_temp = function(plot_df){
  #___________________________ Prep
  # Technology grouping
  groupPV_class_df <- plot_df %>%
    group_by(Year, Class) %>% 
    summarise(num = n(),
              Average_size = mean(Capacity))
  groupPV_class_df$Year = as.numeric(groupPV_class_df$Year)
  # Capacity group
  groupPV_df <- plot_df %>%
    group_by(Year) %>% 
    summarise(num = n(),
              dir_a = sum(Capacity), 
              Average_size = mean(Capacity))
  groupPV_df$Year = as.numeric(groupPV_df$Year)
  # Pull from class split
  single <- groupPV_class_df[which(groupPV_class_df$Class=='single_axis'), ]
  groupPV_df$Avgsize_single <- 0
  groupPV_df$Avgsize_single <- single$Average_size[match(groupPV_df$Year, single$Year)]
  fixed <- groupPV_class_df[which(groupPV_class_df$Class=='fixed_axis'), ] 
  groupPV_df$Avgsize_fixed <- 0
  groupPV_df$Avgsize_fixed <- fixed$Average_size[match(groupPV_df$Year, fixed$Year)] 
  groupPV_class_df$Class[which(groupPV_class_df$Class=="fixed_axis")] <- "Fixed Axis"
  groupPV_class_df$Class[which(groupPV_class_df$Class=="single_axis")] <- "Single Axis"
  # Get graph params
  coeff = (max(groupPV_df$num, na.rm = TRUE) / max(groupPV_df$Avgsize_single, na.rm = TRUE)) %>% plyr::round_any(10, f=floor)
  coeff = ifelse(coeff==0, (max(groupPV_df$num, na.rm = TRUE) / max(groupPV_df$Avgsize_single, na.rm = TRUE)) %>% plyr::round_any(1, f=floor), coeff)
  coeff = ifelse(coeff==0, 0.8, coeff)
  max_y = plyr::round_any(max(groupPV_df$num), 10, f=ceiling)
  graph_name = deparse(substitute(plot_df))
  #___________________________ Plot  
  tech_size_plot <- ggplot(groupPV_df, aes(Year, num)) +
    geom_bar(data=groupPV_class_df, stat ="identity", aes(fill=Class), color = 'white') +
    geom_line(aes(y = Avgsize_fixed*coeff), size=0.5, color="black", linetype=5) + # alpha = 1/3
    geom_line(aes(y = Avgsize_single*coeff), size=0.5, color="black", linetype=5) + # alpha = 1/3
    geom_point(aes(y = Avgsize_fixed*coeff), size=4, color=fixedAxisColor, shape=19) +
    geom_point(aes(y = Avgsize_fixed*coeff), size=4, color="black", shape=21) +
    geom_point(aes(y = Avgsize_single*coeff), size=4, color=singleAxisColor, shape=19) +
    geom_point(aes(y = Avgsize_single*coeff), size=4, color="black", shape=21) +
    scale_fill_manual(values=c(fixedAxisColor, singleAxisColor)) +
    scale_colour_viridis_c(option = "inferno")  +
    scale_y_continuous(name = "Installed Arrays", sec.axis = sec_axis(~./coeff, name="Array Capacity (MW)"), limits = c(0, max_y), expand = c(0,0)) +
    scale_x_continuous(breaks=seq(start_install_year, end_install_year, 1), limits = c(start_install_year-0.5, end_install_year+0.5), expand = c(0,0)) + 
    theme_pubr() + 
    theme(legend.position = "none", plot.title = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), 
          axis.text.x = element_text(angle = 30, vjust = 1, hjust=1), panel.border = element_rect(colour="black", fill=NA, size = 0.75), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
    annotate("text", x = start_install_year-0.5, y=max_y*0.95, label = graph_name, hjust=0, fontface=2)
}
# Get commercial and utility
Commercial <- in_df[which(in_df$Capacity<capacity_threshold),]
Utility <- in_df[which(in_df$Capacity>=capacity_threshold),]
# Get plots
commercial_plot <- getPlot_Array_Tech_Dist_temp(Commercial)
utility_plot <- getPlot_Array_Tech_Dist_temp(Utility)  + theme(axis.text.x = element_blank())
fig <- ggarrange(utility_plot, commercial_plot, nrow = 2, ncol = 1, align = c("v"), heights = c(9,10)) 
fig <- annotate_figure(fig, bottom = text_grob("Installation Year", size = 12), left = text_grob("Number of Installations", size = 12, rot = 90),
                       right = text_grob("Average Array Capacity - - - (MW)", size = 12, rot = 90))

ggsave(path = 'Outputs/Figures', filename = paste("tech_size_dist_", system_lifespan, "yrLS_", capacity_threshold, "MW_", model_name, ".pdf", sep=""), width = 4.35, height = 4.9, units = "in", useDingbats=FALSE)
print(fig)

```